extends: standard
env:
  browser: true
  commonjs: true
  es6: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - standard
  - promise
  - react
rules:
  quotes:
    - error
    - single
  react/jsx-uses-vars: error
  react/jsx-uses-react: error
